export type TAvalilableOptions =
  | 'refresh-icons'
  | 'personalize'
  | 'view-big-icons'
  | 'view-medium-icons'
  | 'view-small-icons'
  | 'view-by-thumbnails'
  | 'view-by-tiles'
  | 'view-by-list'
  | 'view-by-details'
  | 'short-by-name'
  | 'short-by-size'
  | 'short-by-modification Date'
  | 'new-folder'
  | 'new-shortcut';
